server:
  motd: "BeEngine is Good :)"
  max-players: 100
  xbox-require: true
  enable-encryption: true
  debug: false

scheduler:
  # In millis
  timeout: 5000

network:
  ip: "0.0.0.0"
  port: 19132

  compression-level: 7

world:
  default: world

  chunk:
    # In seconds
    expiry-time: 60
    per-tick: 16